version: '3.1'

services:

  kafka:
    container_name: kafka
    image: spotify/kafka
    ports:
      - "9092:9092"
      - "2181:2181"
    hostname: kafka
    expose:
      - "9092"
      - "2181"
    networks:
      - app-net


  db:
    container_name: tebdb
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=teb
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - app-net


  spring:
    image: recretion34/teb
    build: ./
    restart: always
    volumes:
      - ./teblog
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - app-net


networks:
     app-net:
        driver: bridge